English and editorial review of the I-D.
IETF-TEAS-WG/actn-poi pull request #124
Opened 2024-12-17 11:07 UTC by danielkinguk

2025-01-22 13:36 UTC, prmanna approved these changes

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +described in 3.2 provide useful support for Packet Optical Integration
```suggestion
described in {{yang}} provide useful support for Packet Optical Integration
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +- DWDM nodes, as defined in
I-D.ietf-ccamp-optical-impairment-topology-yang defines the 'WDM node' (not the 'DWDM node')

```suggestion
- WDM nodes, as defined in
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +or multi-layer OTN/WDM. In the latter case, multi-layer coordination
```suggestion
or multi-layer OTN/DWDM. In the latter case, multi-layer coordination
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +by a specific IP service on the DWDM equipment).
There is no definition of 'WDM equipment' or 'DWDM equipment'

I think we can use the term 'WDM node' from I-D.ietf-ccamp-optical-impairment-topology-yang as in the rest of the document

```suggestion
by a specific IP service on the WDM node).
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +to report the DWDM network topology (e.g., DWDM nodes and OMS links),
I-D.ietf-ccamp-optical-impairment-topology-yang defines the 'WDM node' (and not the 'DWDM node')

```suggestion
to report the DWDM network topology (e.g., WDM nodes and OMS links),
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +both cases the optical transponders and the DWDM node are under the
I-D.ietf-ccamp-optical-impairment-topology-yang defines the 'WDM node' (and not the 'DWDM node')

```suggestion
transponders are physically integrated within the same WDM node or
are physically located on a device external to the WDM node since it
both cases the optical transponders and the WDM node are under the
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +control of the same O-PNC and abstracted as a single DWDM TE Node at the
I-D.ietf-ccamp-optical-impairment-topology-yang defines the 'WDM TE node' (and not the 'DWDM TE node')

```suggestion
control of the same O-PNC and abstracted as a single WDM TE Node at the
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +intra-domain OTN links are supported by underlay DWDM tunnels: this
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
intra-domain OTN links are supported by underlay WDM tunnels: this
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +The DWDM Tunnel Model is used to report all the DWDM tunnels
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
The WDM Tunnel Model is used to report all the WDM tunnels
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +or transparent. The underlay optical tunnels can be either DWDM
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
or transparent. The underlay optical tunnels can be either WDM
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +The DWDM tunnels can be used to support either Ethernet or CBR client
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
The WDM tunnels can be used to support either Ethernet or CBR client
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +the underlay DWDM tunnel with the supported multi-layer intra-domain
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
the underlay WDM tunnel with the supported multi-layer intra-domain
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +the DWDM Tunnel model or the OTN Tunnel model, if optional OTN switching
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
the WDM Tunnel model or the OTN Tunnel model, if optional OTN switching
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +using the DWDM or OTN tunnel model); and
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
using the WDM or OTN tunnel model); and
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +DWDM tunnel model would also support optical tunnel setup in the case
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
WDM tunnel model would also support optical tunnel setup in the case
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +the DWDM edge node re-configuration so that the IP router's back-up port
I-D.ietf-ccamp-optical-impairment-topology-yang defines the 'WDM node' (and not the 'DWDM node')

```suggestion
that optical layer is fine between the two edge WDM nodes, triggers
the WDM edge node re-configuration so that the IP router's back-up port
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +associated muxponder port can reuse the DWDM tunnel that was already in
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
associated muxponder port can reuse the WDM tunnel that was already in
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +   reconfigured to reuse the existing DWDM tunnel and the new link has
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
   reconfigured to reuse the existing WDM tunnel and the new link has
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +DWDM tunnel as the one used originally for the failed IP router port. Once
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
WDM tunnel as the one used originally for the failed IP router port. Once
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +the back-up port of the IP router and the original DWDM tunnel if overall
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
the back-up port of the IP router and the original WDM tunnel if overall
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +needs to find a DWDM tunnel suitable to comply the DWDM port
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
needs to find a WDM tunnel suitable to comply the DWDM port
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +there is already an existing DWDM tunnel between the two muxponders
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
there is already an existing WDM tunnel between the two muxponders
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +1. if the DWDM tunnel already exists, the controller needs only to
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
1. if the WDM tunnel already exists, the controller needs only to
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +establish the DWDM tunnel, finding a proper optical path matching
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
2. if the WDM tunnel does not exist, the controller has to first
establish the WDM tunnel, finding a proper optical path matching
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +Since multiple client connectivity services are sharing the same DWDM
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
Since multiple client connectivity services are sharing the same WDM
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +request the O-PNC to setup a client connectivity service over a DWDM
I-D.ietf-ccamp-wdm-tunnel-yang defines the 'WDM tunnel' model (and not the 'DWDM tunnel' model)

```suggestion
request the O-PNC to setup a client connectivity service over a WDM
```

2025-01-22 19:51 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> -    name: TBD
I need a placeholder to add a contributor before uploading the I-D on IETF datatracker

2025-01-24 17:06 UTC, jbouqui153 requested changes

2025-01-28 10:14 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +connectivity between IP routers within a single packet domain.;
```suggestion
connectivity between IP routers within a single packet domain.
```

2025-01-28 10:19 UTC, danielkinguk commented on draft-ietf-teas-actn-poi-applicability.md
> +engineered and operated independently. This separation results in
How about... 

...In many current network deployments, packet and optical networks are designed and operated independently. This separation leads to technical disparities between the underlying technologies (e.g., routers versus optical switches) and the associated methods for network engineering and planning (e.g., inter-domain peering...

2025-01-28 14:05 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +falls outside the scope of this document.
**[ACTN POI bi-weekly call (January 28, 2025)](https://github.com/IETF-TEAS-WG/actn-poi/wiki/minutes-2025-01-28)**

```suggestion
Scenarios using coherent optical interfaces on the IP routers are outside the scope of this document.
```

2025-01-28 14:14 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> -    name: TBD
**[ACTN POI bi-weekly call (January 28, 2025)](https://github.com/IETF-TEAS-WG/actn-poi/wiki/minutes-2025-01-28)**

Add back the TBD contributor

2025-01-28 14:17 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +properties, such as Shared Risk Link Group (SRLG).
**[ACTN POI bi-weekly call (January 28, 2025)](https://github.com/IETF-TEAS-WG/actn-poi/wiki/minutes-2025-01-28)**

Need to add a reference to RFC 8001

2025-01-28 14:27 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +engineered and operated independently. This separation results in
The way I read this text is:
- cause: separation of engineering and operations between IP and optical
- consequence: different underlying technologies and methods

IMHO, it should be:
- cause: different underlying technologies and methods
- consequence: separation of engineering and operations between IP and optical

What about:

There are significant technical differences between the packet and optical technologies (e.g.,
routers versus optical switches) and their associated network engineering
and planning approaches (e.g., inter-domain peering optimization in IP
networks versus managing physical impairments in DWDM systems or
operating on vastly different time scales). Additionally, customer
requirements often differ between packet and optical networks, and it is
common for Service Providers to use different vendors for each domain. As
a result, the operation of these complex packet and optical networks is
often siloed, as each technology domain requires specialized skill sets.

As a consequence, in many existing network deployments, packet and optical networks are
engineered and operated independently.

This separation is inefficient for several reasons. First, integrating packet and optical
// see L174 onward

2025-01-28 15:18 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> -    name: TBD
Closed with https://github.com/IETF-TEAS-WG/actn-poi/pull/124/commits/c90c1b31e6bc25610672e6441695e982d55a4892

2025-01-28 15:18 UTC, italobusi commented on draft-ietf-teas-actn-poi-applicability.md
> +properties, such as Shared Risk Link Group (SRLG).
Closed with https://github.com/IETF-TEAS-WG/actn-poi/pull/124/commits/c90c1b31e6bc25610672e6441695e982d55a4892

2025-01-30 16:19 UTC, merged

2025-01-30 16:25 UTC, jbouqui153 commented on draft-ietf-teas-actn-poi-applicability.md
> +engineered and operated independently. This separation results in
Fully agree with your new proposal, Italo. Thanks!